### ISSUE TITLE
执行错误@windows10+python3.7

### ISSUE THREAD

**Issue by ghost** [minejo/kindle-clips#2]
···
Traceback (most recent call last):
  File ".\kindle.py", line 205, in <module>
    main(sys.argv[1:])
  File ".\kindle.py", line 179, in main
    sections = get_sections(FILE_NAME)
UnboundLocalError: local variable 'FILE_NAME' referenced before assignment
···

**Comment by shigure6** [comment]
这个代码太久远了吧，估计很多都不兼容了
